apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: null
    labels:
      component: velero
    name: velero
  spec: {}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    creationTimestamp: null
    labels:
      component: velero
    name: velero
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
  subjects:
  - kind: ServiceAccount
    name: velero
    namespace: velero
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    labels:
      component: velero
    name: velero
    namespace: velero
- apiVersion: v1
  data:
    cloud: W0dsb2JhbF0KdXNlcj1yb290CnBhc3N3b3JkPUh1YXl1bkAxMjMKa2V5PWAtLS0tLUJFR0lOIFJTQSBQUklWQVRFIEtFWS0tLS0tCk1JSUVwQUlCQUFLQ0FRRUF5eVg2WlhWUXNqaDdSRjh4RzVHVlFFcWhuQXB3Y3NvTDdvejBESWw1TTQwTGZDNkIKa2JRTlBjeTdhRWsxMXZ5UVRSTENpY3RCeG9SVXN5TkQ2aXFFRFZpYUZ0RUZNTHBadFlYckFJUkdxSndyc3NkQwo3cFFhUXhLa1pKMGJGY3N2TWRHMWtnNDBPK09OY1E1Ymx4Y3U1WlVXaUUwWkpEUHdBekVEV092cTNMSmsrdFNJClRHYlgxN3EwWlJDT21FWHdmV0s0d1BBV3cybWJVcGNhTjFGdS9kdkNsRTRaVDhkVVNGVEp6dWFQY3h5eVZEbTYKK09mRTNlNFV2MWl3MTBML0xIR0taVU9MdGhQeVJ3MHNUbFVweDdYd3dzSnpwUG92VnUrYWpIcUM1Rk1FWmlMdgpRU2NZb1JCblcvY3AzMWxRNzJPRmpTaDhOeEJ2ZFNDTDN5OURZUUlEQVFBQkFvSUJBUUNLNngyZjQrbWE5aVRWClRJTTRad1c1UVUvaWRRRVFmanBLbHZrTTJiV1lHd3VQai8zcXRVV1l6VGdheUhXWTNuMlBOeFR4UloxbE0zajQKUjFWWi9GanhCM1hYeEhmWUtwYk9HeFhvOUl1ZElhNkFRdUx5WXpUU1NSMUI4RzFsS2R6TUpLd1ZoTUVUY3poMQo1MnVhbHEvckwxaUpQSy9Fb2Yrdkx3VXErYWxSNFROVnY5aTd4ZjJDTDRpQ0g0QllYS2dBQTY5cWIrZk1ncTJvCnhMZmI3enZBVmROcmUzNlBTclBydnB3dWMxZzRRblhlTXNLdFE0bDZySkswL0M0YnFQUWxVNEZudFRYaGNTcUcKOFFYaDg5KzJRRTZYaTh6a1FuUWFHWjVEZGlsKzlGZGVGTlhXWVJpSk51ZHdzUVFadVdaeDExbXlINE1qRFd5dgpBMzV1WmN3QkFvR0JBUGU0R1htRC9GSlhSUjRLcUlCUEFkS0orUUN5cFp2UnM3dWJsb2UrY2RQUVUxR01VRW0vCnkvNUlxVWk3ekM2Z1VtRXdQb2NzN2dIRGJDV3hoT1JjNVNBYWhQRVlQRzREUWhjNjhSQXdIUHdxMUlKYVloYUkKMkFRMHhxRVRNekVlSk5ZZUpTdHZCRmtSckVaOVoxbHlqYlE0UGZTMXVOMk5aU21Id1ZVdmV1MVpBb0dCQU5IdwpkTWh1MnZvVGlFTXNZM2pQRmp2eW5YUExOYy9mR09PVVdYOHZFNUVKRHBiY2xhZEpYd2ZSZ0NNaTZ0QnhaSU00CnhTNnRzQ1plcDRNeXFvKy9EbHVuQ2VZQ2FUS1hGaWJFcWVJUWk3UmRMWEh0WTdoU20vT1ZteXZ3NC8xTGloYkgKVTlabXpCeHpiVnNMa2xpTEp6Q2ZCK001LytkbU56T3JHOTZSNHAxSkFvR0FWOTZ1OHFLMXkwTjNtZnR2Myt1bQptdGNrUTNJYk9wVjlLc3c2N2pYSXpMaTJCVlEvV3BtMU02TDBvWDgwSTBudFR0bzlJOWYxS1J6MzdMcjJoOGJICjQ4WmtaOTBQK25vZlpId2M3SUFVbUFKZFZVdllSV1FQTkJiQWFueVVDUlZIUGNoOXFOVjlkbGJGaEUrUmJISXMKLzhOL2ZxRkRUUnVOeWRpRTVNR3QyaWtDZ1lBTEZXclUraVZOZHFLSENWem5EK2ZZbW1KOXJvalV4SzZIdFZsVQpRYVFDMER1WTgyUmpSSmhqelVlNmt5bGFmK0lTbTNpdGtqWHVrS2kvWUhsb3hXbDRwVVQ4Zzd3U0U2L3p0QVpVCkRST1RIaWc4RDVCb050Uk04K1VSV05Kd21RQmRXNEN0blJmQm1NWjVQQThwNVk3WUhrMUlUZE9ZMytpaUxiSjIKK2JUQklRS0JnUUR6UzYwcEJpcEpuRTdXTXAyNTc0bU5ITDV5cDRXRWpxa2hybjVCU01sb2JwRksrUVM1MDd3SAozUUNuVThZY1dqMlhUcXlXMURDRUdkUmlDaFc4Ly93aXl5Mk9aQmY4cDlTY3pTSm5JSDJYejBmSUZ6MldTVmRsCnhOMDE5VjNnRXYvNGJBaTZESnJIbDY4bnh2TEpSTTJlUkNSSzg4amthYlA4U0p6TnJua0RCdz09Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tYAo=
  kind: Secret
  metadata:
    creationTimestamp: null
    labels:
      component: velero
    name: cloud-credentials
    namespace: velero
  type: Opaque
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: nfs
    namespace: velero
  spec:
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteOnce
    nfs:
      server: 178.104.162.19
      path: "/data/nfs"
    mountOptions:
      - nfsvers=4.1
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: nfs
    namespace: velero
  spec:
    accessModes:
      - ReadWriteOnce
    storageClassName: ""
    resources:
      requests:
        storage: 10Gi
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      component: velero
    name: velero
    namespace: velero
  spec:
    selector:
      matchLabels:
        deploy: velero
    strategy: {}
    template:
      metadata:
        annotations:
          prometheus.io/path: /metrics
          prometheus.io/port: "8085"
          prometheus.io/scrape: "true"
        creationTimestamp: null
        labels:
          component: velero
          deploy: velero
      spec:
        containers:
        - name: sidecar
          image: velero-sidecar-for-metadata:dev
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /credentials
              name: cloud-credentials
            - name: nfs
              mountPath: "/data/nfs"
        - args:
          - server
          - --features=
          command:
          - /velero
          env:
          - name: IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: VELERO_SCRATCH_DIR
            value: /scratch
          - name: VELERO_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: LD_LIBRARY_PATH
            value: /plugins
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /credentials/cloud
          - name: AWS_SHARED_CREDENTIALS_FILE
            value: /credentials/cloud
          - name: AZURE_CREDENTIALS_FILE
            value: /credentials/cloud
          - name: ALIBABA_CLOUD_CREDENTIALS_FILE
            value: /credentials/cloud
          image: velero:dev
          imagePullPolicy: IfNotPresent
          name: velero
          ports:
          - containerPort: 8085
            name: metrics
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 128Mi
          volumeMounts:
          - mountPath: /plugins
            name: plugins
          - mountPath: /scratch
            name: scratch
          - mountPath: /credentials
            name: cloud-credentials
          - name: nfs
            mountPath: "/data/nfs"
        initContainers:
        - image: velero-plugin-for-metadata:dev
          imagePullPolicy: IfNotPresent
          name: velero-plugin-for-metadata
          resources: {}
          volumeMounts:
          - mountPath: /target
            name: plugins
        restartPolicy: Always
        serviceAccountName: velero
        volumes:
        - emptyDir: {}
          name: plugins
        - emptyDir: {}
          name: scratch
        - name: cloud-credentials
          secret:
            secretName: cloud-credentials
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    creationTimestamp: null
    labels:
      component: velero
    name: restic
    namespace: velero
  spec:
    selector:
      matchLabels:
        name: restic
    template:
      metadata:
        creationTimestamp: null
        labels:
          component: velero
          name: restic
      spec:
        containers:
        - args:
          - restic
          - server
          - --features=
          command:
          - /velero
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: VELERO_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: VELERO_SCRATCH_DIR
            value: /scratch
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /credentials/cloud
          - name: AWS_SHARED_CREDENTIALS_FILE
            value: /credentials/cloud
          - name: AZURE_CREDENTIALS_FILE
            value: /credentials/cloud
          - name: ALIBABA_CLOUD_CREDENTIALS_FILE
            value: /credentials/cloud
          image: velero:dev
          imagePullPolicy: IfNotPresent
          name: restic
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
          - mountPath: /host_pods
            mountPropagation: HostToContainer
            name: host-pods
          - mountPath: /scratch
            name: scratch
          - mountPath: /credentials
            name: cloud-credentials
        securityContext:
          runAsUser: 0
        serviceAccountName: velero
        volumes:
        - hostPath:
            path: /var/lib/kubelet/pods
          name: host-pods
        - emptyDir: {}
          name: scratch
        - name: cloud-credentials
          secret:
            secretName: cloud-credentials
    updateStrategy: {}
kind: List
